language: node_js
cache:
  yarn: true
  directories:
  - ~/.npm
notifications:
  email: false
jobs:
  include:
  - stage: release
    node_js: stable
    deploy:
      provider: script
      skip_cleanup: true
      script:
        - npm run semantic-release
script:
- yarn test
